### PR TITLE
Update pt.po

### PR DESCRIPTION
**Pull request by rafaelfelicio**

### CODE REVIEW

**Review by peterzen — CHANGES_REQUESTED** [review]
Some search/replace is needed:
- Bitcoin, bitcoin, bitcoins -> Decred
- BitPay -> Company0

**Comment by rafaelfelicio** [comment]
Modifications made, @peterzen

**Comment by rafaelfelicio** [comment]
Where is Copay, how will you stay?

**Comment by peterzen** [comment]
Thank you @rafaelfelicio – I've imported the file into Transifex and merging it into the release.
https://www.transifex.com/decred/webwallet/

The staging wallet is at https://wallet-staging.decred.org

**Comment by rafaelfelicio** [comment]
It's ok. I applied for access on transifex.

**Comment by alexlyp** [comment]
ok I beleive this has been merged else where.  closing

**Pull request closed without merging**
