### PR TITLE
Use the main network by default.

### LINKED ISSUE #52: Default to mainnet
We've had several instances of people who were confused (reasonably so) that copay defaults to testnet.  Perhaps it is time to switch.

### PR DESCRIPTION
**Pull request by davecgh**
Closes #52

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Trying to get my local copay up and running again but that does look correct to me based.

**Review by jcvernaleo — APPROVED** [review]
I don't have a working copay setup at the moment, but this matches what I remember from when we initially does it and matches up when I compare it to the initial commit (which went from livenet to dcrdtestnet).

**Comment by jcvernaleo** [comment]
Unless @alexlyp objects I'd say merge this in @davecgh

**Comment by alexlyp** [comment]
looks fine to me

**Pull request merged**
